configuration:
  status: warn
  appenders:
    console:
      name: STDOUT
      target: SYSTEM_OUT
      patternLayout:
        pattern: "[%d] [%-5p] [%t] %m%n"
    file:
      name: FILE
      fileName: ./logs/application.log
      patternLayout:
        pattern: "[%d] [%-5p] [%t] %m%n"

  loggers:
    logger:
      name: log.kinki.land
      level: debug
      additivity: true
      appenderRef:
        ref: FILE
    root:
      level: debug
      appenderRef:
        ref: STDOUT