configuration:
  status: debug
  appenders:
    console:
      name: STDOUT
      target: SYSTEM_OUT
      patternLayout:
        pattern: "[%d] [%-5p] [%t] %m%n"
    rollingFile:
      name: FILE
      fileName: "./logs/application.log"
      filePattern: "./logs/application-%d{yyyy-MM-dd}.log.gz"
      patternLayout:
        pattern: "[%d] [%-5p] [%t] %m%n"
      cronTriggeringPolicy:
        schedule: "0 0 0 * * ?"
      defaultRolloverStrategy:
        delete:
          basePath: "./logs"
          ifLastModified:
            age: "P180D"

  loggers:
    logger:
      name: log.kinki.land
      level: debug
      additivity: true
      appenderRef:
        ref: FILE
    root:
      level: debug
      appenderRef:
        ref: STDOUT